# Generated by Django 6.0.3 on 2026-04-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
